<a href="https://colab.research.google.com/github/Ahmad-ullah/NumPy_inGeo/blob/main/Basic_Calculation_20251004.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic Calculation

In [ ]:
Int_1= 475
Int_2= 971

In [ ]:
(
(Int_1 + Int_2),
(Int_2 - Int_1),
(Int_2 / Int_1),
(Int_2 // Int_1),
(Int_2 % Int_1),
(Int_2 * Int_1),
(Int_1 ** 2),
)

(1446, 496, 2.0442105263157893, 2, 21, 461225, 225625)

In [ ]:
Int_3 = 4
Int_4 = 3

In [ ]:
(
(Int_3)*2,
(Int_3)**2,
(Int_3)**(1/2))

(8, 16, 2.0)

In [ ]:
2*(Int_2)- 4*(Int_1)

42

Algebras

In [ ]:
#Algebras
X= 5
Y= 3

In [ ]:
#(X+Y)**2=?
((X**2)+(2*X*Y)+(Y**2))

64

In [ ]:
#(X-Y)**2=?
((X**2)-(2*X*Y)+(Y**2))

4

In [ ]:
#(X**2)-(Y**2) =?
((X+Y)*(X-Y))

16

In [2]:
import numpy as np

In [ ]:
Array_0= np.zeros((7,5))
Array_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
Array_0= np.zeros((7,5), dtype='int')
Array_0

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
Array_0= np.zeros((7,5), dtype='str')
Array_0

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [ ]:
Array_1= np.ones((7,5), dtype='int')
Array_1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
Array_f= np.full((7,5),7, dtype='int')
Array_f

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [3]:
Array_fZ= np.full((7,4),'Z', dtype='str')
Array_fZ

array([['Z', 'Z', 'Z', 'Z'],
       ['Z', 'Z', 'Z', 'Z'],
       ['Z', 'Z', 'Z', 'Z'],
       ['Z', 'Z', 'Z', 'Z'],
       ['Z', 'Z', 'Z', 'Z'],
       ['Z', 'Z', 'Z', 'Z'],
       ['Z', 'Z', 'Z', 'Z']], dtype='<U1')

In [13]:
import numpy as np

In [16]:
VA= np.array([
(1,7,6,9,4),
(7,3,3,1,5),
(9,4,8,2,4),
(8,3,1,4,7)
])
VA

array([[1, 7, 6, 9, 4],
       [7, 3, 3, 1, 5],
       [9, 4, 8, 2, 4],
       [8, 3, 1, 4, 7]])

In [17]:
#Slicing Array
VA [0:3, 1:3]

array([[7, 6],
       [3, 3],
       [4, 8]])

In [18]:
VA [1:3, 0:3]

array([[7, 3, 3],
       [9, 4, 8]])